-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  id integer NOT NULL DEFAULT nextval('app_settings_id_seq'::regclass),
  setting_key text NOT NULL UNIQUE,
  setting_value text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.canceled_credit_notes (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  credit_note_no text NOT NULL,
  irn text NOT NULL,
  cancel_reason_code text NOT NULL,
  cancel_reason text,
  cancelled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT canceled_credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT canceled_credit_notes_credit_note_no_fkey FOREIGN KEY (credit_note_no) REFERENCES public.credit_notes(credit_note_no)
);
CREATE TABLE public.canceled_invoices (
  id integer NOT NULL DEFAULT nextval('canceled_invoices_id_seq'::regclass),
  invoice_no text NOT NULL,
  irn text NOT NULL,
  cancel_reason_code text NOT NULL,
  cancel_reason text,
  cancelled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT canceled_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT canceled_invoices_invoice_no_fkey FOREIGN KEY (invoice_no) REFERENCES public.invoices(invoice_no)
);
CREATE TABLE public.credit_notes (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  unit_id integer NOT NULL,
  credit_note_no text NOT NULL UNIQUE,
  credit_note_date timestamp with time zone NOT NULL DEFAULT now(),
  invoice_no text NOT NULL,
  original_invoice_date timestamp with time zone,
  customer_id integer NOT NULL,
  billing_address text,
  delivery_address text,
  po_number text,
  grade text NOT NULL,
  hsn_code text NOT NULL,
  original_quantity numeric NOT NULL,
  original_rate numeric NOT NULL,
  original_gross_amount numeric NOT NULL,
  original_taxable_amount numeric NOT NULL,
  adjusted_quantity numeric NOT NULL,
  adjusted_rate numeric NOT NULL,
  adjusted_gross_amount numeric NOT NULL,
  adjusted_discount numeric DEFAULT 0,
  adjusted_taxable_amount numeric NOT NULL,
  cgst numeric NOT NULL DEFAULT 0,
  sgst numeric NOT NULL DEFAULT 0,
  igst numeric DEFAULT 0,
  gst_percentage numeric NOT NULL DEFAULT 18.00,
  round_off numeric DEFAULT 0,
  total numeric NOT NULL,
  difference_quantity numeric NOT NULL,
  difference_amount numeric NOT NULL,
  vehicle_no text,
  dc_no text,
  mode_of_transport text DEFAULT 'Road'::text,
  reason_for_credit_note text,
  remarks text,
  credit_note_data jsonb,
  irn text,
  qrcode text,
  ack_no bigint,
  ack_dt timestamp with time zone,
  signed_invoice text,
  einvoice_status text,
  is_cancelled boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  related_invoices ARRAY,
  CONSTRAINT credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT credit_notes_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT credit_notes_invoice_no_fkey FOREIGN KEY (invoice_no) REFERENCES public.invoices(invoice_no),
  CONSTRAINT credit_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id integer NOT NULL DEFAULT nextval('customers_id_seq'::regclass),
  name text NOT NULL,
  gstin text,
  billing_addresses jsonb,
  delivery_addresses jsonb,
  created_at timestamp with time zone DEFAULT now(),
  unit_id integer,
  type text DEFAULT 'B2B'::text CHECK (type = ANY (ARRAY['B2B'::text, 'B2C'::text])),
  trade_name text,
  loc text,
  pin text,
  pan_number text,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id)
);
CREATE TABLE public.delivery_addresses (
  id integer NOT NULL DEFAULT nextval('delivery_addresses_id_seq'::regclass),
  customer_id integer NOT NULL,
  address text NOT NULL,
  loc text,
  pin text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.grades (
  id integer NOT NULL DEFAULT nextval('grades_id_seq'::regclass),
  grade text NOT NULL,
  hsn_code text DEFAULT '38245010'::text,
  rate numeric,
  cement_type text DEFAULT 'OPC-53'::text,
  customer_id integer,
  agg1 numeric DEFAULT 0,
  agg2 numeric DEFAULT 0,
  agg3 numeric DEFAULT 0,
  agg4 numeric DEFAULT 0,
  cem1 numeric DEFAULT 0,
  cem2 numeric DEFAULT 0,
  cem3 numeric DEFAULT 0,
  cem4 numeric DEFAULT 0,
  water numeric DEFAULT 0,
  ice numeric DEFAULT 0,
  admix1 numeric DEFAULT 0,
  admix2 numeric DEFAULT 0,
  is_active boolean DEFAULT false,
  uom_id integer,
  product_description text DEFAULT 'Ready-Mix Concrete'::text,
  is_service text DEFAULT 'N'::text CHECK (is_service = ANY (ARRAY['Y'::text, 'N'::text])),
  unit_ids ARRAY,
  CONSTRAINT grades_pkey PRIMARY KEY (id),
  CONSTRAINT grades_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT grades_uom_id_fkey FOREIGN KEY (uom_id) REFERENCES public.uom(id)
);
CREATE TABLE public.invoices (
  id integer NOT NULL DEFAULT nextval('invoices_id_seq'::regclass),
  unit_id integer,
  invoice_no text NOT NULL UNIQUE,
  invoice_date timestamp with time zone NOT NULL,
  customer_id integer,
  billing_address text,
  delivery_address text,
  grade text,
  hsn_code text,
  quantity numeric,
  rate numeric,
  gross_amount numeric,
  taxable_amount numeric,
  sgst numeric,
  cgst numeric,
  round_off numeric,
  total numeric,
  vehicle_no text,
  dc_no text,
  pump text,
  mode_of_transport text DEFAULT 'Road'::text,
  cement_type text,
  max_agg_size text,
  admixture_type text,
  slump text,
  pouring_location text,
  weather_pumped boolean,
  time_discharge_completed time without time zone,
  time_released_from_site time without time zone,
  water_added_at_site text,
  admixture_added_at_site text,
  remarks text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  po_number text,
  discount numeric DEFAULT 0,
  invoice_data jsonb,
  irn text,
  qrcode text,
  ack_no bigint,
  ack_dt timestamp with time zone,
  signed_invoice text,
  einvoice_status text,
  igst numeric DEFAULT 0.00,
  invoice_type text NOT NULL DEFAULT 'BILLING'::text,
  is_cancelled boolean DEFAULT false,
  gst_percentage numeric NOT NULL DEFAULT 18.00,
  delivery_number text,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.orders (
  id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  customer_id integer,
  grade_id integer,
  order_quantity numeric NOT NULL,
  delivered_quantity numeric DEFAULT 0,
  order_date timestamp with time zone DEFAULT now(),
  expected_delivery_date timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'delivered'::text, 'cancelled'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  po_number text,
  delivery_address text,
  unit_price numeric,
  agg1 numeric DEFAULT 0,
  agg2 numeric DEFAULT 0,
  agg3 numeric DEFAULT 0,
  agg4 numeric DEFAULT 0,
  cem1 numeric DEFAULT 0,
  cem2 numeric DEFAULT 0,
  cem3 numeric DEFAULT 0,
  cem4 numeric DEFAULT 0,
  water numeric DEFAULT 0,
  ice numeric DEFAULT 0,
  admix1 numeric DEFAULT 0,
  admix2 numeric DEFAULT 0,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT orders_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES public.grades(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['operator'::text, 'manager'::text, 'admin'::text])),
  unit_id integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id)
);
CREATE TABLE public.pumps (
  id integer NOT NULL DEFAULT nextval('pumps_id_seq'::regclass),
  pump_name text NOT NULL,
  CONSTRAINT pumps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.purchase_orders (
  id integer NOT NULL DEFAULT nextval('purchase_orders_id_seq'::regclass),
  po_number text NOT NULL UNIQUE,
  po_date timestamp with time zone NOT NULL DEFAULT now(),
  unit_id integer NOT NULL,
  supplier_name text NOT NULL,
  supplier_gstin text,
  supplier_address text,
  stock_id integer NOT NULL,
  quantity_ordered numeric NOT NULL,
  unit_price numeric NOT NULL,
  gst_percentage numeric NOT NULL DEFAULT 18,
  total_cost numeric NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'partial'::text, 'cancelled'::text])),
  invoice_number text,
  invoice_date timestamp with time zone,
  received_quantity numeric DEFAULT 0,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT purchase_orders_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stock_consumptions (
  id integer NOT NULL DEFAULT nextval('stock_consumptions_id_seq'::regclass),
  consumption_number text NOT NULL UNIQUE,
  consumption_date timestamp with time zone NOT NULL DEFAULT now(),
  stock_id integer NOT NULL,
  quantity_used numeric NOT NULL,
  sequence_no bigint,
  dedupe_key text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_consumptions_pkey PRIMARY KEY (id),
  CONSTRAINT stock_consumptions_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id)
);
CREATE TABLE public.stock_entries (
  id integer NOT NULL DEFAULT nextval('stock_entries_id_seq'::regclass),
  entry_number text NOT NULL UNIQUE,
  entry_date timestamp with time zone NOT NULL DEFAULT now(),
  po_id integer,
  po_number text,
  stock_id integer NOT NULL,
  quantity_received numeric NOT NULL,
  vehicle_id integer,
  vehicle_no text,
  remarks text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  entry_source text DEFAULT 'po'::text CHECK (entry_source = ANY (ARRAY['po'::text, 'direct'::text])),
  CONSTRAINT stock_entries_pkey PRIMARY KEY (id),
  CONSTRAINT stock_entries_po_id_fkey FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT stock_entries_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_entries_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT stock_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stocks (
  id integer NOT NULL DEFAULT nextval('stocks_id_seq'::regclass),
  material_name text NOT NULL,
  specific_grade_type text NOT NULL,
  unit_of_measure text NOT NULL CHECK (unit_of_measure = ANY (ARRAY['Tonne'::text, 'Cubic Meter (m³)'::text, 'Bag (50kg)'::text, 'Litre'::text, 'Kilogram'::text])),
  current_quantity numeric DEFAULT 0,
  unit_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stocks_pkey PRIMARY KEY (id),
  CONSTRAINT stocks_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id)
);
CREATE TABLE public.units (
  id integer NOT NULL DEFAULT nextval('units_id_seq'::regclass),
  name text NOT NULL,
  address text,
  city text DEFAULT 'Chennai'::text,
  state text DEFAULT 'Tamil Nadu'::text,
  pincode text DEFAULT '600129'::text,
  gstin text DEFAULT '33AATCA6485H1ZH'::text,
  invoice_count integer NOT NULL DEFAULT 0,
  financial_year text DEFAULT '2025-26'::text,
  loc text,
  credit_note_count integer NOT NULL DEFAULT 0,
  CONSTRAINT units_pkey PRIMARY KEY (id)
);
CREATE TABLE public.uom (
  id integer NOT NULL DEFAULT nextval('uom_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  abbreviation text NOT NULL UNIQUE,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT uom_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehicles (
  id integer NOT NULL DEFAULT nextval('vehicles_id_seq'::regclass),
  unit_id ARRAY,
  vehicle_no text NOT NULL,
  vehicle_type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id)
);